### ISSUE TITLE
初次体验建议汇总

### ISSUE THREAD

**Issue by h619633675** [loamen/Kalman.Studio#7]
你好，非常惊喜在 github 中发现此项目，第一次打开时看见项目很多已经很完善、已经能够满足常用操作的功能。

本来想自己动手写一个代码生成，但为什么要重新造轮子呢，费时间还不一定够完善。

我猜想作者开放出来也是希望更多人使用的，所以下面是初次体验的一些建议，如有出入请见谅。

一、首页说明：

1. 只描述了主要功能，很多常用操作步骤没有说明或者手册，对初次使用者不友好。如:设置连接数据库、批量生成代码、添加模板如何操作。

二、批量化代码：

1. 选择代码模板，如果不选择对应 tt 文件，生成代码会是空白的。

1. 选择 "规范化类名，按Fascal大小写"，生成的代码文件名没有大小写。这个我不确定是否是作者写遗漏了。debug 后发现在 Controller.tt 中的 controllerName 没有使用 className 变量，而是使用 tableName 变量。

1. 希望批量生成代码添加一个选项：在"类名"文件夹名下生成"自定义名"文件。因为如 view 文件夹等,文件名并非会是使用类名，文件多后很难修改。

三、模板文件

作者已经把基础的生成代码模板搭建出来了，自己动手完全可以把后台view/h5，controller，service根据自己的框架生成代码了，但希望可以有更简便、更丰富的模板供使用者挑选，所以后续希望可以有比如

1. 当前语言环境下，基础环境模板选择，增删改查基础接口外，其它比如token效验cors配置等基础环境。  
(如 .net framework ， .net core, html 中 ui 框架的基础环境)

1. 基础环境模板对应选择生成代码模板，即开始看到各类语言的代码模板。

四、最后

感谢作者开放代码，我后续会尝试使用这个项目创建一个代码模板，预计

api 使用 .net core, java, php ...

UI 为 可能是 js/ts 写的 h5 , UI 框架 juqery(layui), vue+element/bootstrap ...

**Comment by loamen** [comment]
- 感谢楼主提出的意见，Kalman Studio是十年前的一个项目。原作者很早就没有维护了，几年前征求原作者意见后一直由本人一个人在维护，但是本人因工作原因精力实在有限，所以很久没有更新了。
- 关于使用方法的问题，如果之前试用过动软代码生成器的应该都会用，比较简单。
- 其实我之前发现有很多人修改了很多功能自己在用或者在自己公司内部在用，我看了部分的截图其实是功能都是很不错的。
- 如果大家觉得本项目有用，我呼吁大家都能Fork本项目并贡献你的代码，让.Net的开源生态圈真正活跃起来。
